sonar.projectKey=sw-construction-project
sonar.projectName=SW Construction Project

sonar.sources=dataset/refactored
sonar.java.binaries=dataset/refactored

sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}